config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  get 'homes/index'
  get "tweets/search"
  root to: 'homes#index'
  resources :users do
    get :following, :followers, :user_tweets
  end
  resources :relationships, only: [:create, :destroy]
  resources :data, only: :index
  resources :tweets do
    resources :comments, only: [:create, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates :comment, presence: true
end

app/models/datum.rb
class Datum < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' }, { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' }, { id: 6, name: '山形県' },
    { id: 7, name: '福島県' }, { id: 8, name: '茨城県' }, { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' }, { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' }, { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' }, { id: 17, name: '石川県' }, { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' }, { id: 20, name: '長野県' }, { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' }, { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' }, { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' }, { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' }, { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' }, { id: 35, name: '山口県' }, { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' }, { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' }, { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' }, { id: 44, name: '大分県' }, { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :tweets
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :data
  has_one_attached :image
  has_one_attached :item_image
  has_many_attached :memory_images

  with_options presence: true do
    validates :title
    validates :start_time
    validates :image
    validates :prefecture_id
    validates :place
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
  has_many :data

  validates :nickname, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :congfigure_permitted_parameters, if: :devise_controller?

  private

  def congfigure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/tweets/#{comment.tweet.id}"
  end

  def destroy
    @comment = Comment.find(params[:tweet_id])
    @comment.destroy
    redirect_to "/tweets/#{@comment.tweet_id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :user_signed

  def index
    user = User.find(current_user.id)
    @tweet = user.tweets
  end

  private

  def user_signed
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :basic_auth

  def index
    if user_signed_in?
      redirect_to tweets_path(current_user.id)
    end
  end

  def show
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :basic_auth

  def index
    redirect_to tweets_path(current_user.id) if user_signed_in?
  end

  def show
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :user_signed
  before_action :tweets_params, only: [:show, :edit, :update, :destroy]
  before_action :search_tweets, only: [:index, :search]

  def index
    user = User.find(current_user.id)
    @tweets = user.tweets.order(id: 'DESC')
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      redirect_to tweets_path(current_user.id)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    if @tweet.user.id == current_user.id
      @tweet.destroy
      redirect_to tweets_path(current_user.id)
    end
  end

  def search
    @results = @p.result.includes(:user)
    @tweets = Tweet.includes(:user)
  end

  def self.search(search)
    Tweet.where('place LIKE(?)', "%#{search}%") if serch != ''
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :start_time, :image, :item_image, :prefecture_id, :place, :wanted_list,
                                  memory_images: []).merge(user_id: current_user.id)
  end

  def tweets_params
    @tweet = Tweet.find(params[:id])
  end

  def user_signed
    redirect_to new_user_session_path unless user_signed_in?
  end

  def search_tweets
    @p = Tweet.ransack(params[:q])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="holder">
    <div class="txt">
      <h1>Camp! camp! camp!</h1>
      <p>Let's camping!!</p>
    </div>
</div>
  <div class="area">
    <h2>キャンプを愛する人の</h2>
    <h2>キャンプを愛する人による</h2>
    <h2>キャンプを愛する人のためのアプリ</h2>   
  </div>
<div class="holder2">
  <div class="txt1">
  <ul>
    <li class="txt2"><h1>最新のキャンプをすぐに確認！</h1></li>
    <li class="txt2"><h1>キャンプの思い出をまとめて保存！</h1></li>
    <li class="txt2"><h1>みんなでシェアしてさらに楽しく！</h1></li>
    <li class="txt2"><h1>アイテムもいっしょに保存！</h1></li>
    <li class="txt2"><h1>過去に行ったキャンプ場がすぐにわかる！</h1></li>
    <li class="txt2"><h1>欲しいものをその場で検索！</h1></li>
    </ul>
    <%= link_to "Learn More","#"%>
</div>
</div>

<%= render "shared/hooter"%>

app/views/homes/index.html.erb
<div class="holder">
    <div class="txt">
      <h1>Camp! Camp! Camp!</h1>
      <p>Let's camping!!</p>
    </div>
</div>
  <div class="area">
    <h2>あなたが求めていたものは</h2>
    <h2>キャンプだけの思い出を綴る</h2>
    <h2>キャンプ専用アプリではないでしょうか？</h2>   
  </div>
<div class="holder2">
  <div class="txt1" data-delighter>
  <ul>
    <li class="txt2"><h1>自分だけのためのアプリがついに登場！</h1></li>
    <li class="txt2"><h1>最新のキャンプをすぐに確認！</h1></li>
    <li class="txt2"><h1>キャンプの思い出をまとめて保存！</h1></li>
    <li class="txt2"><h1>アイテムもいっしょに保存！</h1></li>
    <li class="txt2"><h1>過去に行ったキャンプ場がすぐにわかる！</h1></li>
    <li class="txt2"><h1>欲しいものをその場で検索！</h1></li>
    <li><%= link_to "Learn More","#"%><li>
  </ul>

</div>
</div>

<%= render "shared/hooter"%>

app/views/tweets/edit.html.erb
<%= render "shared/form"%>

app/views/tweets/index.html.erb
<body class="index-body">
  <div class='foto-contents'>
    <h2 class='title'>最近のキャンプ</h2>
    <div class="previews">
      <ul class="autoplay">
        <% @tweets.last(10).each do |tweet|%>
          <li class='foto-list'>
            <%= link_to tweet_path(tweet.id) do %>
              <% if tweet.image.attached?%>
                <div><%= image_tag tweet.image, class: "foto-img" %></div>
                <div class="foto-content"><%= tweet.title%></div>
              <% end %>
            <%end%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

<%# キャンプ場名 %>
  <div class='place-contents'>
      <h2 class='title'>キャンプ場名</h2>
      <ul class='place-lists'>
        <% @tweets.last(6).each do |tweet|%>
          <li class='list'>
            <%= link_to tweet_path(tweet.id) do %>
              <div class='place-name'>
                <h3> <%= tweet.place %> </h3>
              </div>
            <%end%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

<%# カレンダー %>
  <%= month_calendar events:@tweets do | date, tweets| %>
    <%= date.day %>
    <% tweets.each do |tweet| %>
      <div>
        <%= link_to tweet.title, tweet, class:"calender-contents" %>
      </div>
    <% end %>
  <% end %>

<%# 欲しいものリスト%>
  <div class='wanted-contents'>
    <h2 class='title'>欲しいものリスト</h2>

  <%# リスト表示 %>
      <div class='item-lists'>
        <% @tweets.last(8).select do |tweet|%>
          <% if tweet.wanted_list!="" %>
            <div class='item-info'>
              <%= tweet.wanted_list %>
            </div>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>

  <%# google検索・結果表示 %>
  <div class="google">
    <script async src="https://cse.google.com/cse.js?cx=ee7493856c23b6f7f"></script>
    <div class="gcse-searchbox-only"></div>
    <div class="google-result">
      <script async src="https://cse.google.com/cse.js?cx=ee7493856c23b6f7f"></script>
      <div class="gcse-searchresults-only"></div>
    </div>
  </div>
</body>

app/views/tweets/new.html.erb
<%= render "shared/form" %>

app/views/tweets/search.html.erb
<body class="new-body">
  <div class= "main-new">
    <div class= "main-new2">
      <div class="search-title">
        キャンプ場検索一覧
      </div>
      <ul class="search">
        <%= search_form_for @p, url:tweets_search_path do |f|%>
        <li class= "search-list">
          <%= f.label  "都道府県"%>
          <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name, include_blank: "全て"%>
        </li>
        <li class= "search-list"><%= f.search_field :place_cont, placeholder: "キャンプ場名" %></li>
        <li class= "search-button"><%= f.submit "検索"%></li>
        <%end%>
      </ul>

      <ul class="search-result">
        <%if @results.length !=0%>
          <% @results.each do |result|%>
            <li class="search-result-list">
            <%= link_to tweet_path(result.id), class:"result-link" do %>
              <%= result.prefecture.name%>
              <%= result.place%>
            </li>
            <%end%>
          <%end%>
        <%else%>
          <h1>
          検索結果：該当なし
          </h1>
          <br/>
          <% @tweets.each do |tweet|%>
            <li class="search-result-list">
              <%= tweet.prefecture.name%>
              <%= tweet.place%>
            </li>
          <%end%>
        <%end%>
      </ul>
    </div>
  </div>
</body>

app/views/tweets/show.html.erb
<body class="show-body">
  <div class="show-main">
  
    <%# 訪問日/タイトル/キャンプ場の場所%>
    <div class="date-title">
      <%= @tweet.start_time.strftime("%Y-%m-%d")%>
      <%= @tweet.title%>
    </div>
    <div class="date-title">
        <%= @tweet.prefecture.name%>
        <%= @tweet.place %>
    </div>

    <%# メンバーとの写真%>
    <div class="camping-title">
    今日のキャンパー達
    </div>
    <div class="camping-member">
      <%= image_tag @tweet.image.variant(resize:"500x500") %>
    </div>

    <%# アイテム紹介%>
    <div class="todays-item">
    今日のアイテム
    </div>
    <div class="item-photo-show">
      <% if @tweet.item_image.attached?%>
        <%=image_tag @tweet.item_image.variant(resize:"500x500"), id:"item-photo"%>
      <% end %>
    </div>

  <%# キャンプの様子%>
    <div class="camping-memory">
      最高のキャンプ！！
    </div>
    <div class="memory-photo-show">
      <% if @tweet.memory_images.attached?%>
        <% @tweet.memory_images. each do |tweet|%>
          <%= image_tag tweet.variant(resize:"500x500")%>
        <%end%>
      <%end%>
    </div>

  <%# 欲しいものリスト%>
    <div class="list-show">
    欲しいものリスト
    </div>
    <div class="show-wanted">
        <% if @tweet.wanted_list.present?%>
        <%= @tweet.wanted_list%>
        <% end %>
    </div>

  <%#コメント%>
    <div class="show-memo">
    思い出メモ
    </div>
    <div class="comment-show">
      <%= form_with model: [@tweet, @comment], local: true do |f|%>
        <%= f.text_area :comment, placeholder: "思い出メモ"%>
        <br/>
        <%= f.submit "comment"%>
      <% end %>
     </div>
      <%if @comments.present? %>
        <% @comments.each do |comment|%>
          <p>
            <span class="comment-contents">
              <%= comment.comment%>
            </span>
            <%= link_to "✖︎", tweet_comment_path(comment.id), method: :delete %>
          </p>
        <%end%>
      <%end%>



    <%#おまけコメント%>
    <div class="balloon3-right-btm">
      YOU HAVE GOOD MEMORY! :)
    </div>

    <%# ボタン %>
    <div class="next-back-home">
      <div class="back">
        <%= link_to "Back",tweets_path(current_user.id)%>
      </div>
      <div class="edit">
        <%= link_to "Edit", edit_tweet_path(@tweet.id), method: :get %>
      </div>
      <div class="delete">
        <%= link_to "Delete",tweet_path(@tweet.id), method: :delete%>
      </div>
  </div>
</body>